#!/bin/bash
### BEGIN INIT INFO
# Provides:          openvpn-startup
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Starts OpenVPN client with pre-configured profile
### END INIT INFO
openvpn --config /home/user/user-1-config.ovpn

